# Generated by Django 6.0.1 on 2026-04-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_user_approval_note_user_approval_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="类型名称"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=100, verbose_name="排序"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="说明"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "活动类型",
                "verbose_name_plural": "活动类型",
                "db_table": "activity_type",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="other_type",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="其他类型补充"
            ),
        ),
    ]
