# Generated by Codex on 2026-04-11

from django.db import migrations


DEFAULT_ACTIVITY_TYPES = [
    "环境保护",
    "敬老助残",
    "社区服务",
    "文明宣传",
    "应急救援",
    "大型活动保障",
    "其他",
]


def seed_activity_types(apps, schema_editor):
    ActivityType = apps.get_model("api", "ActivityType")
    Activity = apps.get_model("api", "Activity")

    for index, name in enumerate(DEFAULT_ACTIVITY_TYPES, start=1):
        ActivityType.objects.get_or_create(
            name=name,
            defaults={
                "sort_order": index,
                "is_active": True,
                "description": "",
            },
        )

    existing_type_names = set(ActivityType.objects.values_list("name", flat=True))
    dynamic_sort = 100
    for type_name in Activity.objects.values_list("type", flat=True).distinct():
        if not type_name:
            continue
        if type_name not in existing_type_names:
            ActivityType.objects.create(
                name=type_name,
                sort_order=dynamic_sort,
                is_active=True,
                description="历史活动类型自动迁移",
            )
            existing_type_names.add(type_name)
            dynamic_sort += 1


def rollback_seed(apps, schema_editor):
    ActivityType = apps.get_model("api", "ActivityType")
    ActivityType.objects.filter(name__in=DEFAULT_ACTIVITY_TYPES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_activitytype_activity_other_type"),
    ]

    operations = [
        migrations.RunPython(seed_activity_types, rollback_seed),
    ]
